### PR TITLE
set -coq_expand_list_types option to false by default

### PR DESCRIPTION
**Pull request by palmskog**
Since `-coq_expand_list_types false` arguably generates the most straightforward Coq code (no introduction of new terminals/non-terminals compared to the Ott source, no extra utility functions to keep track of), I think it should be the default. The only "extra" Coq code with this option is for the induction principle, which can be easily ignored if not needed.

For context, I have been using this option explicitly for years in lots of Ott-based projects, without code generation problems.

### CODE REVIEW

**Comment by francesco-zappa-nardelli** [comment]
> The only "extra" Coq code with this option is for the induction principle, which can be easily ignored if not needed.

Back in the days that was important for usability but I guess (hope) that the Scheme command can now generate the correct induction principle if native lists are used? If it is the case we might just remove the generation of the induction principle. 

-francesco (from phone)

**Comment by palmskog** [comment]
Unfortunately, the `Scheme` command still can't generate a useful principle when an inductive type has a nested inductive such as lists (although `Scheme` for mutually defined inductives works well).

The state of the art is to use the [Equations plugin](https://github.com/mattam82/Coq-Equations), which at least enables a straightforward encoding of the induction principle:
```coq
Require Import List. Import ListNotations.
From Equations Require Import Equations.

Inductive tree {A : Type} : Type :=
  | atom : A -> tree
  | node : list tree -> tree.

Section tree_ind2.
Variable A : Type.
Variable P : @tree A -> Prop.
Variable P_list : list (@tree A) -> Prop.
Hypothesis P_nil : P_list [].
Hypothesis P_cons : forall t l, P t -> P_list l -> P_list (t :: l).
Hypothesis P_atom : forall a, P (atom a).
Hypothesis P_node : forall l, P_list l -> P (node l).

Equations tree_ind2 (t : @tree A) : P t :=
{ tree_ind2 (atom a) := P_atom a;
  tree_ind2 (node l) := P_node l (tree_ind2_list l) }
where tree_ind2_list (l : list (@tree A)) : P_list l :=
{ tree_ind2_list [] := P_nil;
  tree_ind2_list (tn :: l') := P_cons tn l' (tree_ind2 tn) (tree_ind2_list l') }.

End tree_ind2.
```
However, rather than using something like Equations, I think it's better to continue to rely on code generation using `Fixpoint` for the time being.

**Comment by palmskog** [comment]
@hannesm this is the last contribution I have for a while - if you could do a release soon that would be convenient. Or let me know if you're busy and I can do the release (probably late next week, if so).

**Comment by hannesm** [comment]
@palmskog I released ott 0.30 and opened a PR to opam-repository at https://github.com/ocaml/opam-repository/pull/15380
I'll shortly PR a release.txt here which contains the steps to cut a release

**Comment by PeterSewell** [comment]
(thanks!)

**Pull request merged**
