### PR TITLE
introduce explicit Coq universes for metavars

### PR DESCRIPTION
**Pull request by palmskog**
The absence of a `coq-universe` hom for metavars recently bit me in an Ott-based [Coq project](https://github.com/proofengineering/regmatch/tree/qed-at-large), where I had to use a sed-based hack to make the project compile.

 This PR introduces explicit universes (defaulting to `Set`) for metavars, and enables the `coq-universe` hom for metavars. This change could potentially break a project, e.g., if the underlying type of the metavar currently lives in the `Type` sort. However, it should be obvious how to fix compilation for those cases (adding `{{ coq-universe Type }}`). I didn't have any problems with my projects or the bundled OCaml Light example.

I'm not sure if there was a specific reason for not making universes configurable for metavars, since "everything else" seems to have configurable universes.

### CODE REVIEW

**Comment by palmskog** [comment]
@francesco-zappa-nardelli since (I believe) you wrote the metavar code generation for Coq, do you possibly recall if there is some hidden gotcha or straightforward justification for why metavar universes are currently implicit?

**Comment by francesco-zappa-nardelli** [comment]
> @francesco-zappa-nardelli since (I believe) you wrote the metavar code generation for Coq, do you possibly recall if there is some hidden gotcha or straightforward justification for why metavar universes are currently implicit?

I _believe_ the only reason is that we did not have any use for anything fancier in our experiments.

-francesco

**Comment by palmskog** [comment]
Thanks, then it seems to make sense to add this now, since the universe handling has gotten much more sophisticated in Coq over the years, e.g.,
```coq
Universe u.
Inductive h : Type@{u} := h1.
Definition h' : Type@{u+1} := h.
Fail Definition h'' : Type@{u} := h'.
```
I will do some final tests and merge later today.

**Comment by francesco-zappa-nardelli** [comment]
> Thanks, then it seems to make sense to add this now, since the universe handling has gotten much more sophisticated in Coq over the years...   I will do some final tests and merge later today.

The locally nameless backend should probably ignore the new hom, or do the right thing.

-francesco

**Comment by palmskog** [comment]
Thanks for flagging up the nameless stuff. I noticed now that to even test the nameless backend, I actually need to fix some Coq code generation issues. At least the people at UPenn are maintaining the Metalib project [on GitHub](https://github.com/plclub/metalib) now, and it works with recent Coq.

**Comment by francesco-zappa-nardelli** [comment]
Thanks!  It is great if this code can be kept functional.

-francesco

**Comment by sweirich** [comment]
+1 

We are still using the locally nameless backend at Penn. Let me know if there is a way we can help with testing.

Thanks,
Stephanie

**Comment by palmskog** [comment]
@sweirich Thanks for offering to help out. I actually went through a bunch of examples related to lngen just now and hand-checked that the same Coq source (up to improvements) were generated and were fine according to `coqc`. Is it OK if we add the Ott source of your STLC and LF_hhp93 examples to the Ott test suite? There are apparently no locally-nameless test cases in the suite right now, and it would be good to have to check for regressions in the future.

Since the tooling for testing the full stack (Ott/Coq/lngen/metatheory/...) is somewhat complicated to set up, maybe we can arrange some more testing on Penn projects after the next Ott release is out?

**Comment by sweirich** [comment]
Thanks for your work, Karl! No issue with including the examples in the Ott test suite, I’m glad that they will be supported.

Best,
Stephanie

**Pull request merged**
