### PR TITLE
Adds the ability to rename inference rules when Tex filtering.

### PR DESCRIPTION
**Pull request by heades**
Originally, Ott did not allow one to easily rename an inference rule
in Tex.  For example, in an Ott specification one might define a rule
like the following:

```
G, x : A |- t : B
-------------------- :: Fun
G |- \x:A.t : A -> B
```

Unfortunately, Ott does not provide any means of giving a Tex version of
the name "Fun". 

Given the previous rule Ott would generate the following LaTex
(assuming no prefix was given to Ott, and that the judgment prefix is
"T_"):

```
\newcommand{\OttdruleTXXFun}[1]{\Ottdrule[#1]{%
\Ottpremise{\Gamma \Ottsym{,}  \mathit{x}  \Ottsym{:}  \Ottnt{A}  \vdash  \Ottnt{t}  \Ottsym{:}  \Ottnt{B}}%
}{
\Gamma \vdash   \lambda  \mathit{x}  :  \Ottnt{A} . \Ottnt{t}   \Ottsym{:}  \Ottnt{A}  \to  \Ottnt{B}}{%
{\Ottdrulename{T\_Fun}}{}%
}}
```

We can see that the name of the rule "T\_Fun" is not easily changed within LaTex.  

We fix this issue by having Ott factor out the name of each rule into
a constant LaTex command that can be renewed in LaTex.  Now given the
rule above Ott will generate the following:

```
\newcommand{\OttdruleTXXFunName}[0]{\Ottdrulename{T\_Fun}}
\newcommand{\OttdruleTXXFun}[1]{\Ottdrule[#1]{%
\Ottpremise{\Gamma \Ottsym{,}  \mathit{x}  \Ottsym{:}  \Ottnt{A}  \vdash  \Ottnt{t}  \Ottsym{:}  \Ottnt{B}}%
}{
\Gamma \vdash   \lambda  \mathit{x}  :  \Ottnt{A} . \Ottnt{t}   \Ottsym{:}  \Ottnt{A}  \to  \Ottnt{B}}{%
{\OttdruleTXXFunName}{}%
}}
```

Then to rename the rule we can simply add the following after the Ott
generated LaTex include file has been importanted:

```
\renewcommand{\OttdruleTXXFunName}[0]{$\rightarrow_I$}
```

I felt that this modification was the least problematic when it comes
to backward compatibility.

### CODE REVIEW

**Comment by dorchard** [comment]
This is an extremely useful feature

**Comment by dorchard** [comment]
Any chance of this getting in?

**Comment by cyberglot** [comment]
@tperami Could you have a look at this and possibly merge it? It's a very useful that would be nice to have.

**Comment by PeterSewell** [comment]
I've not looked at the diff, but from the previous messages this looks
reasonable to me - except that to reduce the risk of accidental name
clashes between rules, better use a suffix that's less likely to occur in
the user's rule names, not just "Name"

\OttdruleTXXFunName

**Comment by heades** [comment]
Yeah, Peter I can do that!  I'll make that change and send a new PR either
today or tomorrow.

Best, Harley

**Comment by yallop** [comment]
This'd be a useful feature.  @heades, are you still planning to change the suffix?

**Comment by heades** [comment]
Yup! Just been busy. I’ll get it done next week for sure.

Harley

**Comment by dorchard** [comment]
Any update on this @heades ?

**Comment by heades** [comment]
I just took care of this; finally.  Sorry for the delay.

I'm sending a PR now.

The commands for renaming rule are:

\ottPrefixRenameRuleRuleName

where ottPrefix is the prefix set by the -tex_prefix option. So by default
commands are:

\renewcommand{\ottRenameRuleVar}{Axiom}

will rename the Var rule to Axiom.

So the names of these commands shouldn't conflict anymore.

Harley

**Pull request closed without merging**
