### PR TITLE
OCaml 5.0 compatibility

### PR DESCRIPTION
**Pull request by bacam**
- update names of relevant library modules/functions
- replace embedded ocamlgraph with installed copy using ocamlfind

Note: with this pull request #95 is unnecessary, because the embedded copy of the library has gone away.

### CODE REVIEW

**Comment by tperami** [comment]
Sorry, but some of the boring dependency stuff is missing:
 - Add `ocamlgraph` as a dependency in the `opam` file.
 - Figure out the minimum (and maybe maximum) version of `ocamlgraph` that work
 - Figure out the new minimum version of OCaml needed (I expect at least 4.08, but I'm not sure).

**Comment by tperami** [comment]
Ok this is ready to be merged for me

**Comment by kit-ty-kate** [comment]
FYI, the full release of OCaml 5.0 is planned to be released next week

**Comment by bacam** [comment]
I don't have write access to this repo, so someone who does will have to merge it.

**Pull request merged**
