### PR TITLE
Fix HOL library compatibility with kananaskis-13

### PR DESCRIPTION
**Pull request by palmskog**
We are aiming to use Ott (and Lem) for various tasks in the [HolBA](https://github.com/kth-step/HolBA) project. To this end, here's a small update to the Ott HOL library to make it compile in kananaskis-13. I've also tested it with HOL4 `master` as of November 2019.

### CODE REVIEW

**Comment by palmskog** [comment]
This seems to work well for several Ott projects I tested it on (e.g., [fitch](https://github.com/palmskog/fitch) and [regmatch](https://github.com/proofengineering/regmatch)), so merging.

**Comment by hannesm** [comment]
would you like an opam release? (feel free to do it yourself, but I could as well do one this week)

**Comment by palmskog** [comment]
@hannesm sure, how about you do the release sometime after Wednesday (Nov 20)?

One change I was contemplating for the next release (triggered by a recent email discussion) was to set the option `-coq_expand_list_types` to `false` by default, which appears to me to be the reasonable choice for almost any conceivable Ott-dependent Coq project nowadays.

@mpwassell @PeterSewell @francesco-zappa-nardelli any objections to changing this default?

**Comment by PeterSewell** [comment]
On Mon, 18 Nov 2019, 18:08 Karl Palmskog, <notifications@github.com> wrote:

> @hannesm <https://github.com/hannesm> sure, how about you do the release
> sometime after Wednesday (Nov 20)?
>
> One change I was contemplating for the next release (triggered by a recent
> email discussion) was to set the option -coq_expand_list_types to false
> by default, which appears to me to be the reasonable choice for almost any
> conceivable Ott-dependent Coq project nowadays.
>
> @mpwassell <https://github.com/mpwassell> @PeterSewell
> <https://github.com/PeterSewell> @francesco-zappa-nardelli
> <https://github.com/francesco-zappa-nardelli> any objections to changing
> this default?
>
None from me

**Comment by francesco-zappa-nardelli** [comment]
If the generated coq still compiles, I am all for it. Thanks. 

-francesco (from phone)

**Pull request merged**
