### PR TITLE
Make error messages consistently formatted with locations

### PR DESCRIPTION
**Pull request by JoeyEremondi**
Fixed version of #37.

There are two main effects of this change. First, all error messages are printed using the same formatting, for consistency and ease of parsing. Secondly, location information is included in error messages whenever possible.

Now, error messages have the following format:

```
File filename on loc:
Error: error message text
```
For example:
```
File ../tests/test10st.ott on line 55, column 7 - 81:
Warning: Free variables in hom element [[G2]]
```

While there are a lot of changes, very little of the functionality of Ott is changed, since the changes only affect printing of errors. I've run the tests, and on my machine this causes no regressions.

~~Note that this PR also includes the changes from #40.~~ This change is now independent of #40.

### CODE REVIEW

**Comment by PeterSewell** [comment]
This error message fixing sounds uncontroversially a good thing.

The #40 diff is not so clear - without looking at the code, I'd guess that
the original bug is a lack of a "principle ntr of ntr" call somewhere, so
I'm a bit suspicious of adding a separate bounds coalescing phase.   No
time to properly look now, though - apologies!

**Comment by JoeyEremondi** [comment]
@PeterSewell fair enough, would you like me to resubmit without the changes from #40 ?

**Comment by PeterSewell** [comment]
Yes please

**Comment by JoeyEremondi** [comment]
@PeterSewell Okay, I've updated this PR to be independent of #40.

**Pull request merged**
